# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


title: Kurama Okubo
author: Kurama OKUBO
author_ja: 大久保　蔵馬
url: "https://kura-okubo.github.io"
baseurl: "" 

markdown: kramdown

tracking_id: UA-127973434-1 #Google Analytics Tracking ID

include:
  - .htaccess
  - _pages

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Original page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jekyll-sitemap

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


timezone: Europe/Paris # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


nav:
 - name: "Home"
   link: "/index.html"
 - name: "CV"
   link: "/contents/cv_okubo.pdf"
 - name: "News"
   link: "/news.html"
 - name: "Research"
   link: "/research.html"
 - name: "Publication"
   link: "/publication.html"
 - name: "Contact"
   link: "/contact.html"

nav_ja:
 - name: "ホーム"
   link: "/index_ja.html"
 - name: "CV"
   link: "/contents/cv_okubo.pdf"
 - name: "ニュース"
   link: "/news.html"
 - name: "研究内容"
   link: "/research.html"
 - name: "出版物(論文)"
   link: "/publication.html"
 - name: "お問い合わせ"
   link: "/contact.html"


# for page in Japanese
index_ja: "/index_ja.html" 


